source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RCounter_Example', :exclusive => true do
  pod "RCounter", :path => "../"
end

target 'RCounter_Tests', :exclusive => true do
  pod "RCounter", :path => "../"

  
end
